config/routes.rb
Gprofiles::Application.routes.draw do

  resources :profiles do
    resources :nodes
  end

  root :to => 'profiles#index'
end

app/models/node.rb
require 'cpp_method'

class Node < ActiveRecord::Base
  has_and_belongs_to_many :parents, :join_table              => :relationships,
                                    :class_name              => 'Node',
                                    :foreign_key             => :child_id,
                                    :association_foreign_key => :parent_id
  has_and_belongs_to_many :children, :join_table              => :relationships,
                                     :class_name              => 'Node',
                                     :foreign_key             => :parent_id,
                                     :association_foreign_key => :child_id

  belongs_to :profile

  attr_accessor :pids

  validates_presence_of :nid
  validates_presence_of :profile_id
  validates_presence_of :label
  validates_presence_of :weight
  validates_uniqueness_of :nid, :scope => :profile_id

  def Node.parse( profile, chunk )
    #          1         2                3           4            5 = rest
    #          id        time             self        children     called   name
    rgx = /^\[(\d+)\]\s+(\d+\.\d+)\s{4}(\d+\.\d+)\s{4}(\d+\.\d+)\s+(.*)$/
    m = chunk.match( rgx )
    raise "root line not found in '#{ chunk }'" if m.nil?
    start     = m.pre_match
    nid       = m[ 1 ].to_i
    weight    = m[ 2 ].to_f
    rest      = m[ 5 ]

    # strip call count
    rest.gsub!( /^\d+(\/\d+)?\s+/, '' )
    m        = rest.match( /^(.*?)\s+\[\d+\]$/ )
    raise "unexpected rest format: #{ rest }" if m.nil?
    label    = m[ 1 ]
    label    = 'main()' if label == 'main'

    pids = []
    while m = start.match( /\[(\d+)\]$/ )
      pids << m[ 1 ].to_i
      start = m.post_match
    end

    Node.create!( :nid        => nid,
                  :pids       => pids,
                  :weight     => weight,
                  :label      => label,
                  :profile_id => profile.id)
  end

  def info
    ( ! method.class_name.blank? ? "#{ method.class_name }::" : '' ) + "#{ method.method }() (#{ weight }%)"
  end

  def method
    @method ||= CppMethod.new( label )
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :nodes

  def parse!( gprof )
    raw   = gprof.read
    nodes = parse_raw( raw )
    set_parent( nodes )
    self
  end

  def root
    nodes.order( 'id' ).first
  end

  private

  def parse_raw( raw )
    nodes = []
    each_chunk( raw ) do | chunk |
      nodes << Node.parse( self, chunk )
    end
    nodes
  end

  def each_chunk( raw )
    # skip to the first entry
    start = raw.match( /index\s+%\s+time\s+self.*\n/ )
    raise "start not found" if start.nil?
    rest  = start.post_match
    lines = rest.split(/^-{10,}/)
    lines.pop # lose the doc page and index
    lines.each do | line |
      yield line
    end
  end

  def set_parent( nodes )
    nodes.each do | node |
      node.pids.each do | pid |
        parent = self.nodes.find_by_nid( pid )
        if parent
          node.parents << parent
        end
      end
    end
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :child, :class_name => 'Node', :foreign_key => :child_id
  belongs_to :parent, :class_name => 'Node', :foreign_key => :parent_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  def show
    @profile = Profile.find( params[ :profile_id ] )
    @node    = @profile.nodes.find( params[ :id ] )
  end

end

app/controllers/profiles_controller.rb
# -*- coding: utf-8 -*-
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find( params[ :id ] )
  end

  def new
    @profile = Profile.new
  end

  def create
    gprof    = params[ :profile ].delete( :gprof )
    @profile = Profile.create!( params[ :profile ] )
    @profile.parse!( gprof )
    redirect_to profile_url( @profile )
  end

  def edit
    @profile = Profile.find( params[ :id ] )
  end

  def update
    gprof    = params[ :profile ].delete( :gprof )
    @profile = Profile.find( params[ :id ] )
    @profile.update_attributes( params[ :profile ] )
    @profile.nodes.delete_all
    @profile.parse!( gprof )

    redirect_to profile_url( @profile )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gprofiles</title>
  <%= stylesheet_link_tag :all %>
  <%# javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nodes/show.haml
%p
- @node.parents.each do |parent|
  %a{ :title => parent.label, :href => profile_node_path( @profile, parent ) }
    = parent.info
  != '&nbsp;'
%br
|
%br
v
%br
%h3{ :title => @node.label }
  = @node.info
|
%br
v
%br
- @node.children.each do |child|
  %a{ :title => child.label, :href => profile_node_path( @profile, child ) }
    = child.info
  != '&nbsp;'
%br

app/views/profiles/_form.haml
- form_for @profile, :html => { :multipart => true } do |form|
  = form.text_field :title
  = form.file_field :gprof
  = form.submit

app/views/profiles/edit.haml
= render :partial => 'form'

app/views/profiles/index.haml
%ul
  - @profiles.each do |profile|
    %li
      = link_to( profile.title, profile_node_url( profile, profile.root ) )
  %li
    = link_to( 'add', new_profile_url )

app/views/profiles/new.haml
= render :partial => 'form'

app/views/profiles/show.haml
%ul
  %li= @profile.title
  %li= link_to 'edit', edit_profile_url( @profile )
  %li= link_to 'browse', profile_node_url( @profile, @profile.root )